name: gh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mypy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.7"
      
      - name: "set up mypy"
        run: pip install mypy
      
      - name: "check mypy"
        run: mypy . --strict
  black:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.7"
      
      - name: "set up black"
        run: pip install black
      
      - name: "check black"
        run: black . --check
