name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  example1:
    runs-on: "ubuntu-latest"
    steps:
    - name: aa
      run: echo "example 1 passed"
  example2:
    runs-on: "ubuntu-latest"
    steps:
      - name: aa
        run: echo "example 2 passed"
